### ISSUE TITLE
What's this thing capable of? :)

### ISSUE THREAD

**Issue by e00dan** [Rebelworks/ember-feature-flag-solution#1]
Hey, I'd like to ask what's this repo currently:
1) able to do
2) missing

And I believe there's dependency of ember-feature-flags? :)

**Comment by Cryrivers** [comment]
Hi there! Thanks for the question. `ember-feature-flag-solution` tries to implement conditional compilation in `JavaScript`, `HTMLBars` template and `SCSS` stylesheets by providing a function named `featureFlag` in JavaScript, a helper named `feature-flag` in `HTMLBars` and exporting feature flags as SCSS variables. So far it works and I'm currently using it for my production build. My use case is to have a project targeted to multiple countries and multiple environments (say `test`, `sandbox` and `staging`) with only one single branch, which simplifies our development and deployment process. We don't mess up with our code while merging two branches because we don't have to. That's a great time-saver for us. :)

What's missing, first thing is inline support for the helper `feature-flag`. You cannot do `{{if (feature-flag 'someFeature') 'enabled' 'disabled'}}`, only `{{#if (feature-flag 'someFeature')}}{{/if}}`.

Last but pretty important I think is documentation. I don't have much time for documentation at this moment. Maybe I need to spend some time on it :)

EDIT: btw, there isn't dependency of `ember-feature-flags`. It has different use cases.

**Comment by Cryrivers** [comment]
I'm closing this issue since no more discussion here.

**Comment by tehmaestro** [comment]
Hi, I love the idea behind this addon, just what I was looking for. 
So for templates, the usage would be:
```
    {{#if (feature-flag 'myFeature')}}
      {{my-feature-component}}
    {{/if}}
```
Could post a quick example of how to use this addon in js and sass? Thanks a lot.
